// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cdidemo.proto

package cdiproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the search string.
type SearchRequest struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Userid               string   `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Passwd               string   `protobuf:"bytes,3,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb996b86c1d7a629, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *SearchRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *SearchRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type UserRequest struct {
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb996b86c1d7a629, []int{1}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *UserRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type JsonResponse struct {
	Jsondata             string   `protobuf:"bytes,1,opt,name=jsondata,proto3" json:"jsondata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonResponse) Reset()         { *m = JsonResponse{} }
func (m *JsonResponse) String() string { return proto.CompactTextString(m) }
func (*JsonResponse) ProtoMessage()    {}
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb996b86c1d7a629, []int{2}
}

func (m *JsonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonResponse.Unmarshal(m, b)
}
func (m *JsonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonResponse.Marshal(b, m, deterministic)
}
func (m *JsonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonResponse.Merge(m, src)
}
func (m *JsonResponse) XXX_Size() int {
	return xxx_messageInfo_JsonResponse.Size(m)
}
func (m *JsonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JsonResponse proto.InternalMessageInfo

func (m *JsonResponse) GetJsondata() string {
	if m != nil {
		return m.Jsondata
	}
	return ""
}

type ValidResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidResponse) Reset()         { *m = ValidResponse{} }
func (m *ValidResponse) String() string { return proto.CompactTextString(m) }
func (*ValidResponse) ProtoMessage()    {}
func (*ValidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb996b86c1d7a629, []int{3}
}

func (m *ValidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidResponse.Unmarshal(m, b)
}
func (m *ValidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidResponse.Marshal(b, m, deterministic)
}
func (m *ValidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidResponse.Merge(m, src)
}
func (m *ValidResponse) XXX_Size() int {
	return xxx_messageInfo_ValidResponse.Size(m)
}
func (m *ValidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidResponse proto.InternalMessageInfo

func (m *ValidResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "cdiproto.SearchRequest")
	proto.RegisterType((*UserRequest)(nil), "cdiproto.UserRequest")
	proto.RegisterType((*JsonResponse)(nil), "cdiproto.JsonResponse")
	proto.RegisterType((*ValidResponse)(nil), "cdiproto.ValidResponse")
}

func init() {
	proto.RegisterFile("cdidemo.proto", fileDescriptor_eb996b86c1d7a629)
}

var fileDescriptor_eb996b86c1d7a629 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0xc7, 0xb7, 0xfd, 0xd8, 0xd6, 0x3d, 0xbf, 0x55, 0x24, 0xe8, 0x1c, 0x3b, 0x49, 0x41, 0x10,
	0x0f, 0xc3, 0x3f, 0x37, 0x75, 0xca, 0x6c, 0x25, 0xa8, 0xb7, 0x88, 0x7a, 0x8e, 0xcb, 0x23, 0xab,
	0xcc, 0xa6, 0x36, 0xa9, 0xe2, 0xeb, 0xf4, 0x0d, 0x49, 0x9b, 0x6e, 0x6d, 0x0f, 0xee, 0x10, 0x6f,
	0xfd, 0x7e, 0xc8, 0xf7, 0xd3, 0xe7, 0x49, 0xc0, 0x9d, 0x89, 0x50, 0xe0, 0x9b, 0x1c, 0xc7, 0x89,
	0xd4, 0x92, 0x38, 0x33, 0x11, 0xe6, 0x5f, 0xde, 0x13, 0xb8, 0xf7, 0xc8, 0x93, 0xd9, 0x9c, 0xe1,
	0x7b, 0x8a, 0x4a, 0x93, 0x01, 0x74, 0x54, 0x0e, 0x86, 0xcd, 0xdd, 0xe6, 0x7e, 0x8f, 0x15, 0x29,
	0xe3, 0xa9, 0xc2, 0x24, 0x14, 0xc3, 0x96, 0xe1, 0x26, 0x65, 0x3c, 0xe6, 0x4a, 0x7d, 0x8a, 0xe1,
	0x3f, 0xc3, 0x4d, 0xf2, 0x26, 0xf0, 0xff, 0x41, 0x61, 0x52, 0xd1, 0x16, 0xf5, 0xe6, 0x2f, 0xf5,
	0x56, 0xad, 0x7e, 0x00, 0xfd, 0x5b, 0x25, 0x23, 0x86, 0x2a, 0x96, 0x91, 0x42, 0x32, 0x02, 0xe7,
	0x55, 0xc9, 0x48, 0x70, 0xcd, 0x0b, 0xc3, 0x2a, 0x7b, 0x7b, 0xe0, 0x3e, 0xf2, 0x45, 0x28, 0x56,
	0x87, 0xb7, 0xa0, 0xfd, 0x91, 0x81, 0xfc, 0xa4, 0xc3, 0x4c, 0x38, 0xfe, 0x6e, 0x43, 0xd7, 0x37,
	0xd7, 0x40, 0xce, 0xc1, 0x99, 0xa6, 0x7a, 0x9e, 0x4d, 0x48, 0xb6, 0xc7, 0xcb, 0xdb, 0x18, 0x57,
	0x26, 0x1e, 0xed, 0x94, 0xb8, 0x66, 0xf7, 0x1a, 0xe4, 0x14, 0xba, 0x14, 0xf5, 0xba, 0xf2, 0xa0,
	0xc4, 0xd5, 0x35, 0xbc, 0x06, 0xb9, 0x04, 0xa0, 0xa8, 0xef, 0xf0, 0xcb, 0x97, 0x02, 0x49, 0xe5,
	0x27, 0xb5, 0x67, 0x58, 0x23, 0xb8, 0x86, 0xcd, 0x52, 0x10, 0xa0, 0xe6, 0xe1, 0xc2, 0x46, 0x73,
	0x05, 0x6e, 0xa9, 0x61, 0xf8, 0x62, 0xe3, 0x98, 0x80, 0x43, 0x51, 0xdf, 0xf8, 0xc1, 0xd1, 0xa1,
	0x4d, 0xdd, 0x87, 0x8d, 0x65, 0xdd, 0x7e, 0x8f, 0x0b, 0xe8, 0x19, 0x49, 0x62, 0xb7, 0xc3, 0x19,
	0x74, 0x28, 0xea, 0x80, 0x51, 0x9b, 0xf2, 0x14, 0xfa, 0xa6, 0xfc, 0xd7, 0xf9, 0x03, 0x46, 0xed,
	0xe6, 0x7f, 0xee, 0xe4, 0xf4, 0xe4, 0x27, 0x00, 0x00, 0xff, 0xff, 0x30, 0x5b, 0x96, 0x9b, 0xe2,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CdidemoClient is the client API for Cdidemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CdidemoClient interface {
	AuthUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ValidResponse, error)
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetKeyCode(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetKeyCodeDetail(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetKeyCodeRef(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetICD10(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetICD10Detail(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetICDref(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetDRG(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetDRGDetail(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetDRGref(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type cdidemoClient struct {
	cc grpc.ClientConnInterface
}

func NewCdidemoClient(cc grpc.ClientConnInterface) CdidemoClient {
	return &cdidemoClient{cc}
}

func (c *cdidemoClient) AuthUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ValidResponse, error) {
	out := new(ValidResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/AuthUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetKeyCode(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetKeyCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetKeyCodeDetail(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetKeyCodeDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetKeyCodeRef(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetKeyCodeRef", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetICD10(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetICD10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetICD10Detail(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetICD10Detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetICDref(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetICDref", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetDRG(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetDRG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetDRGDetail(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetDRGDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdidemoClient) GetDRGref(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/cdiproto.Cdidemo/GetDRGref", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CdidemoServer is the server API for Cdidemo service.
type CdidemoServer interface {
	AuthUser(context.Context, *UserRequest) (*ValidResponse, error)
	GetUser(context.Context, *UserRequest) (*JsonResponse, error)
	GetKeyCode(context.Context, *SearchRequest) (*JsonResponse, error)
	GetKeyCodeDetail(context.Context, *SearchRequest) (*JsonResponse, error)
	GetKeyCodeRef(context.Context, *SearchRequest) (*JsonResponse, error)
	GetICD10(context.Context, *SearchRequest) (*JsonResponse, error)
	GetICD10Detail(context.Context, *SearchRequest) (*JsonResponse, error)
	GetICDref(context.Context, *SearchRequest) (*JsonResponse, error)
	GetDRG(context.Context, *SearchRequest) (*JsonResponse, error)
	GetDRGDetail(context.Context, *SearchRequest) (*JsonResponse, error)
	GetDRGref(context.Context, *SearchRequest) (*JsonResponse, error)
}

// UnimplementedCdidemoServer can be embedded to have forward compatible implementations.
type UnimplementedCdidemoServer struct {
}

func (*UnimplementedCdidemoServer) AuthUser(ctx context.Context, req *UserRequest) (*ValidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUser not implemented")
}
func (*UnimplementedCdidemoServer) GetUser(ctx context.Context, req *UserRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedCdidemoServer) GetKeyCode(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyCode not implemented")
}
func (*UnimplementedCdidemoServer) GetKeyCodeDetail(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyCodeDetail not implemented")
}
func (*UnimplementedCdidemoServer) GetKeyCodeRef(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyCodeRef not implemented")
}
func (*UnimplementedCdidemoServer) GetICD10(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetICD10 not implemented")
}
func (*UnimplementedCdidemoServer) GetICD10Detail(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetICD10Detail not implemented")
}
func (*UnimplementedCdidemoServer) GetICDref(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetICDref not implemented")
}
func (*UnimplementedCdidemoServer) GetDRG(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDRG not implemented")
}
func (*UnimplementedCdidemoServer) GetDRGDetail(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDRGDetail not implemented")
}
func (*UnimplementedCdidemoServer) GetDRGref(ctx context.Context, req *SearchRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDRGref not implemented")
}

func RegisterCdidemoServer(s *grpc.Server, srv CdidemoServer) {
	s.RegisterService(&_Cdidemo_serviceDesc, srv)
}

func _Cdidemo_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/AuthUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).AuthUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetKeyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetKeyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetKeyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetKeyCode(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetKeyCodeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetKeyCodeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetKeyCodeDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetKeyCodeDetail(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetKeyCodeRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetKeyCodeRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetKeyCodeRef",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetKeyCodeRef(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetICD10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetICD10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetICD10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetICD10(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetICD10Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetICD10Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetICD10Detail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetICD10Detail(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetICDref_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetICDref(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetICDref",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetICDref(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetDRG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetDRG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetDRG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetDRG(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetDRGDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetDRGDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetDRGDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetDRGDetail(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cdidemo_GetDRGref_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdidemoServer).GetDRGref(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdiproto.Cdidemo/GetDRGref",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdidemoServer).GetDRGref(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cdidemo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdiproto.Cdidemo",
	HandlerType: (*CdidemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthUser",
			Handler:    _Cdidemo_AuthUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Cdidemo_GetUser_Handler,
		},
		{
			MethodName: "GetKeyCode",
			Handler:    _Cdidemo_GetKeyCode_Handler,
		},
		{
			MethodName: "GetKeyCodeDetail",
			Handler:    _Cdidemo_GetKeyCodeDetail_Handler,
		},
		{
			MethodName: "GetKeyCodeRef",
			Handler:    _Cdidemo_GetKeyCodeRef_Handler,
		},
		{
			MethodName: "GetICD10",
			Handler:    _Cdidemo_GetICD10_Handler,
		},
		{
			MethodName: "GetICD10Detail",
			Handler:    _Cdidemo_GetICD10Detail_Handler,
		},
		{
			MethodName: "GetICDref",
			Handler:    _Cdidemo_GetICDref_Handler,
		},
		{
			MethodName: "GetDRG",
			Handler:    _Cdidemo_GetDRG_Handler,
		},
		{
			MethodName: "GetDRGDetail",
			Handler:    _Cdidemo_GetDRGDetail_Handler,
		},
		{
			MethodName: "GetDRGref",
			Handler:    _Cdidemo_GetDRGref_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdidemo.proto",
}
